### ISSUE TITLE
จำนวนก้าวไม่ตรงกับในแอปสุขภาพ

### ISSUE THREAD

**Issue by JcsnP** [Four-Horsemen-of-the-SWE/MyPace#5]
- ทุกครั้งที่ logout แล้วเข้าใหม่ จำนวนก้าวจะลดลง
- จำนวนก้าวไม่ตรงกับในแอป

**Comment by Sarithh** [comment]
ใช่ควัฟ

**Comment by JcsnP** [comment]
**เนื่องจากตอนแรกโค้ดที่ใช้เป็นการเขียนในลักษณะนี้**
```js
const end = new Date();
const start = new Date();
start.setDate(end.getDate() - 1);  // <------ ตรงนี้เป็นการกำหนดค่าให้ดึงถึงเมื่อวาน
Pedometer.getStepCountAsync(start, end).then(
    ...
 );
```

ซึ่งเป็นการดึงข้อมูลการเดินจาก **`วันที่และเวลาปัจจุบัน`** ย้อนไปถึง **`เวลาที่ตรงกับตอนนี้ของเมื่อวาน`**  เนื่องจากผู้ใช้งานไม่ได้ขยับไปไหน (ซึ่ง @Sarithh และ @JcsnP  ทีเป็นคนทดสอบก็นั่งเขียนโค้ดอยู่เฉยๆ ไม่ได้ขยับไปไหน) ทำให้ก้าวเดินที่ดึงมายิ่งน้อยลงเรื่อยๆ

**แก้ไขโดยการเปลี่ยนจากดึงข้อมูลของเมื่อวานจนถึงตอนนี้เป็นการดึงข้อมูลการเดินของวันนี้แทน**
```js
const end = new Date();
const start = new Date();
start.setHours(0,0,0,0);    // <------ ใส่อันนี้ลงไปแทน
Pedometer.getStepCountAsync(start, end).then(
    ...
 );
```

**ผลลัพธ์**
![image](https://user-images.githubusercontent.com/37466531/207940073-8426e492-4b07-41bb-bf66-0fa3225c018f.png)

**แก้ไขโค้ด**
![image](https://user-images.githubusercontent.com/37466531/207939906-e76eb9d1-df67-41d5-834b-e9a8c4d0c773.png)
